env:
  browser: true
  es2022: true
extends:
  - 'eslint:recommended'
  - 'plugin:@typescript-eslint/recommended'
parser: '@typescript-eslint/parser'
plugins:
  - '@typescript-eslint'
  - 'simple-import-sort'
root: true
rules:
  no-console: error
  # Non-null assertions used for refs in solidJS
  '@typescript-eslint/no-non-null-assertion': 0
  '@typescript-eslint/no-unused-vars':
    - error
    - varsIgnorePattern: ^_
  '@typescript-eslint/explicit-function-return-type':
    - error
    - allowExpressions: true

  simple-import-sort/imports:
    - error
